#!/usr/bin/env python3
# coding: utf-8

# Python 2-3 compatibility.
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

if __name__ == '__main__':
    from clewn import vim
    vim.main()
